Catch error when getting release tag and quit

diff --git a/.github/workflows/update_release_assets.yml b/.github/workflows/update_release_assets.yml
--- a/.github/workflows/update_release_assets.yml
+++ b/.github/workflows/update_release_assets.yml
@@ -57,6 +57,10 @@ jobs:
       - name: Get latest release tag
         run: |
           LATEST_TAG=$(curl -s -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/ra1nb0rn/search_vulns/releases/latest | jq -r '.tag_name')
+          if [[ -z $LATEST_TAG || $LATEST_TAG == "null" ]]; then
+            echo "error: could not get latest release tag"
+            exit 1
+          fi
           echo "LATEST_RELEASE_TAG=$LATEST_TAG" >> $GITHUB_ENV
       - name: Update resource files of latest release
         uses: softprops/action-gh-release@v2
